version: '3'

volumes:
  btc-db-data:

services:
  app:
    container_name: better_together-core-app
    build: .
    command: bash -c "rm -f spec/dummy/tmp/pids/server.pid && cd ./spec/dummy && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/better_together-core
    ports:
      - "3000:3000"
    depends_on:
      - db
      - bundler
    environment:
      TRAVIS: ${TRAVIS}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}
  db:
    container_name: better_together-core-db
    image: mdillon/postgis:latest
    volumes:
      - btc-db-data:/var/lib/postgresql/data
  bundler:
    container_name: better_together-core-bundler
    image: busybox
    volumes:
      - .:/bundler
