version: '3.6'

volumes:
  btc-db-data:
  btc-bundler-gems:

services:
  app:
    container_name: better_together-community-app
    build: .
    command: bash -c "rm -f spec/dummy/tmp/pids/server.pid && cd ./spec/dummy && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - btc-bundler-gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  db:
    container_name: better_together-community-db
    image: mdillon/postgis:latest
    volumes:
      - btc-db-data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
