---
openapi: 3.0.1
info:
  title: Community Engine API V1
  version: v1
paths:
  "/bt/api/v1/people":
    post:
      summary: Create a person
      tags:
      - People
      parameters: []
      responses:
        '201':
          description: person created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: api.bebettertogether.ca
